__MAKE_ENTRY__(sqrt) __COMMA__
__MAKE_ENTRY__(abs) __COMMA__
__MAKE_ENTRY__(exp) __COMMA__
__MAKE_ENTRY__(log) __COMMA__
__MAKE_ENTRY__(log10) __COMMA__
__MAKE_ENTRY__(sin) __COMMA__
__MAKE_ENTRY__(cos) __COMMA2__
__MAKE_ENTRY2__(erf) __COMMA2__
__MAKE_ENTRY2__(erfc) __COMMA2__
__MAKE_ENTRY2__(tgamma) __COMMA2__
__MAKE_ENTRY2__(lgamma) __COMMA2__
__MAKE_ENTRY2__(cbrt) __COMMA2__
__MAKE_ENTRY2__(tan) __COMMA2__
__MAKE_ENTRY2__(asin) __COMMA2__
__MAKE_ENTRY2__(acos) __COMMA2__
__MAKE_ENTRY2__(atan) __COMMA2__
__MAKE_ENTRY2__(sinh) __COMMA2__
__MAKE_ENTRY2__(cosh) __COMMA2__
__MAKE_ENTRY2__(tanh) __COMMA2__
__MAKE_ENTRY2__(asinh) __COMMA2__
__MAKE_ENTRY2__(acosh) __COMMA2__
__MAKE_ENTRY2__(atanh)
#undef __MAKE_ENTRY__
#undef __COMMA__
#undef __MAKE_ENTRY2__
#undef __COMMA2__
